dist: trusty
sudo: require

language: python
python:
  - "2.7"

branches:
  only:
  - travis
  - /^s200-\d+\.\d+\.\d+$/

notifications:
  email: false

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  pip: true
  directories:
  - "~/.platformio"

env:
  - TEST_PLATFORM="LPC1768"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/share/tests/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${TRAVIS_BUILD_DIR}/buildroot/share/tests/:${PATH}

install:
  #- pip install -U platformio
  - pip install -U https://github.com/platformio/platformio-core/archive/master.zip

  # Update PlatformIO packages
  - platformio update

before_script:
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  #
  # Generate custom version include
  #- generate_version ${TRAVIS_BUILD_DIR}/Marlin/src/inc
  - generate_version ${TRAVIS_BUILD_DIR}/Marlin/
  - pwd
  - ls -la
  #- cat ${TRAVIS_BUILD_DIR}/Marlin/src/inc/_Version.h
  - cat ${TRAVIS_BUILD_DIR}/Marlin/Version.h
  #
script:
  #- run_tests ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  - platformio run
  - ls -l .pioenvs/LPC1768/firmware.bin


deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: .pioenvs/LPC1768/firmware.bin
  skip_cleanup: true
  overwrite: true
  draft: true
  on: 
    all_branches: true
  #   tags: true